// Package tor manages a private tor instance that registers the site as a
// hidden service (both HTTP and gemini) automatically.
package tor

import (
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/charmbracelet/log"
)

// Forward maps one onion virtual port to a local listener.
type Forward struct {
	VirtualPort int    // port on the onion side (80, 1965, 22, 23, …)
	LocalAddr   string // local listen address (":80", "127.0.0.1:8080", …)
}

// Manager runs and supervises the tor subprocess.
type Manager struct {
	Binary   string
	DataDir  string // starpulse data dir; tor state goes in <DataDir>/tor
	Forwards []Forward
	Log      *log.Logger

	cmd   *exec.Cmd
	onion string
}

// Onion returns the hidden service hostname once known ("" before that).
func (m *Manager) Onion() string { return m.onion }

// Start launches tor and waits (briefly) for the onion hostname.
func (m *Manager) Start() error {
	if _, err := exec.LookPath(m.Binary); err != nil {
		return fmt.Errorf("tor binary %q not found in PATH (install tor or disable tor in config): %w", m.Binary, err)
	}

	torDir := filepath.Join(m.DataDir, "tor")
	hsDir := filepath.Join(torDir, "hidden_service")
	dataDir := filepath.Join(torDir, "state")
	for _, d := range []string{torDir, dataDir} {
		if err := os.MkdirAll(d, 0o700); err != nil {
			return err
		}
	}
	// tor insists on 0700 for the HS dir
	if err := os.MkdirAll(hsDir, 0o700); err != nil {
		return err
	}

	torrc := filepath.Join(torDir, "torrc")
	conf, err := torrcContent(dataDir, hsDir, m.Forwards)
	if err != nil {
		return err
	}
	if err := os.WriteFile(torrc, []byte(conf), 0o600); err != nil {
		return err
	}

	m.cmd = exec.Command(m.Binary, "-f", torrc, "--quiet")
	m.cmd.Stdout = os.Stderr
	m.cmd.Stderr = os.Stderr
	if err := m.cmd.Start(); err != nil {
		return fmt.Errorf("starting tor: %w", err)
	}
	m.Log.Info("tor started", "pid", m.cmd.Process.Pid)

	go func() {
		if err := m.cmd.Wait(); err != nil {
			m.Log.Error("tor exited", "err", err)
		}
	}()

	// the hostname file appears once tor has generated/loaded the service key
	hostFile := filepath.Join(hsDir, "hostname")
	for i := 0; i < 60; i++ {
		if raw, err := os.ReadFile(hostFile); err == nil {
			m.onion = strings.TrimSpace(string(raw))
			m.Log.Info("hidden service ready", "onion", m.onion)
			return nil
		}
		time.Sleep(500 * time.Millisecond)
	}
	m.Log.Warn("tor did not publish a hostname within 30s; continuing without onion")
	return nil
}

// Stop terminates the tor subprocess.
func (m *Manager) Stop() {
	if m.cmd != nil && m.cmd.Process != nil {
		_ = m.cmd.Process.Kill()
	}
}

// torrcContent renders the generated torrc: one HiddenServicePort per
// enabled door, so everything the config turns on is reachable via onion.
func torrcContent(dataDir, hsDir string, forwards []Forward) (string, error) {
	if len(forwards) == 0 {
		return "", fmt.Errorf("tor enabled but no services to forward")
	}
	var b strings.Builder
	fmt.Fprintf(&b, `# generated by starpulse — do not edit (regenerated on start)
SocksPort 0
DataDirectory %s
HiddenServiceDir %s
`, dataDir, hsDir)
	for _, f := range forwards {
		port, err := portOf(f.LocalAddr)
		if err != nil {
			return "", fmt.Errorf("cannot derive local port for onion:%d from %q: %w", f.VirtualPort, f.LocalAddr, err)
		}
		fmt.Fprintf(&b, "HiddenServicePort %d 127.0.0.1:%s\n", f.VirtualPort, port)
	}
	return b.String(), nil
}

// portOf extracts the port from a listen address like ":1965" or "0.0.0.0:80".
func portOf(addr string) (string, error) {
	_, port, err := net.SplitHostPort(addr)
	if err != nil {
		return "", err
	}
	if port == "" {
		return "", fmt.Errorf("no port in %q", addr)
	}
	return port, nil
}
