// Package highlight renders syntax-highlighted code blocks server side, so
// the public site needs no JavaScript to show colourful code.
//
// Gemtext already carries the language: the alt text on a preformatted
// fence. ```go, ```python and so on are looked up as lexers; a fence with no
// alt text, or an unknown one, is left as plain preformatted text.
package highlight

import (
	"fmt"
	"strings"
	"sync"

	"github.com/alecthomas/chroma/v2"
	"github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/lexers"
	"github.com/alecthomas/chroma/v2/styles"
)

// Highlighter renders code with a light and a dark palette.
type Highlighter struct {
	light, dark *chroma.Style
	formatter   *html.Formatter

	once sync.Once
	css  string
}

// New builds a highlighter. Unknown style names fall back to sensible
// defaults rather than failing.
func New(lightName, darkName string) *Highlighter {
	light := styles.Get(lightName)
	if light == nil || lightName == "" {
		light = styles.Get("github")
	}
	dark := styles.Get(darkName)
	if dark == nil || darkName == "" {
		dark = styles.Get("github-dark")
	}
	return &Highlighter{
		light: light,
		dark:  dark,
		// classes, not inline styles: one stylesheet, cacheable, and it can
		// switch with the reader's colour scheme
		formatter: html.New(html.WithClasses(true), html.WithLineNumbers(false)),
	}
}

// Languages reports whether a fence alt text names a lexer we can highlight.
func Known(lang string) bool { return lexerFor(lang) != nil }

func lexerFor(lang string) chroma.Lexer {
	lang = strings.TrimSpace(strings.ToLower(lang))
	if lang == "" {
		return nil
	}
	// alt text is free-form; take the first word ("go", "sh — an example")
	if i := strings.IndexAny(lang, " \t,;"); i > 0 {
		lang = lang[:i]
	}
	switch lang {
	case "banner", "table", "ascii", "art", "text", "txt":
		return nil // decorative blocks starpulse already treats specially
	}
	return lexers.Get(lang)
}

// Render returns highlighted HTML for code, and false when the language is
// unknown (the caller should fall back to plain preformatted output).
func (h *Highlighter) Render(lang, code string) (string, bool) {
	lexer := lexerFor(lang)
	if lexer == nil {
		return "", false
	}
	iter, err := lexer.Tokenise(nil, code)
	if err != nil {
		return "", false
	}
	var b strings.Builder
	if err := h.formatter.Format(&b, h.light, iter); err != nil {
		return "", false
	}
	return b.String(), true
}

// CSS returns the stylesheet for highlighted code.
//
// Both palettes are scoped to their own prefers-color-scheme query. Leaving
// the light one unscoped would leak: a style names only the token classes it
// colours, so any class the light palette defines and the dark one omits
// (punctuation, for one) would keep its near-black colour on a dark
// background. Where neither query matches, code simply inherits the page's
// own foreground, which is readable by construction.
func (h *Highlighter) CSS() string {
	h.once.Do(func() {
		var b strings.Builder
		b.WriteString("/* generated by starpulse from chroma styles */\n")
		b.WriteString(scoped("(prefers-color-scheme: light)", h.cssFor(h.light)))
		b.WriteString(scoped("(prefers-color-scheme: dark)", h.cssFor(h.dark)))
		h.css = b.String()
	})
	return h.css
}

func (h *Highlighter) cssFor(style *chroma.Style) string {
	var b strings.Builder
	_ = h.formatter.WriteCSS(&b, style)
	return b.String()
}

func scoped(query, css string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "\n@media %s {\n", query)
	for _, line := range strings.Split(css, "\n") {
		if strings.TrimSpace(line) == "" {
			continue
		}
		fmt.Fprintf(&b, "  %s\n", line)
	}
	b.WriteString("}\n")
	return b.String()
}

// StyleNames lists the palettes available for configuration.
func StyleNames() []string { return styles.Names() }
